### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by yjeanrenaud** [nalajcie/tuya-cloud-to-influxdb#20]
```
/home/user/tuya-cloud-to-influxdb/lib/common.js:31
    if (def.property.type === 'value') {
                     ^

TypeError: Cannot read properties of undefined (reading 'type')
    at /home/user/tuya-cloud-to-influxdb/lib/common.js:31:22
    at Array.forEach (<anonymous>)
    at Object.getDeviceMeasurement (/home/user/tuya-cloud-to-influxdb/lib/common.js:26:24)
    at /home/user/tuya-cloud-to-influxdb/cli.js:75:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
```

**Comment by nalajcie** [comment]
Sorry but I don't have any Tuya devices anymore (I've converted them to Tasmota FW for easier integration with HA).

When You raise an issue, it would be great to write steps to reproduce - from the backtrace I assume You've tried to get the current data from some device. Probably the error relates to some changes in API on Tuya servers. 

You can verify it by enabling debug output:
```bash
DEBUG=* ./cli.js show
```
(You will see the raw JSON data being sent/received)
